site_name: MANY
site_url: https://shinylegion.github.io/many

theme:
  name: material
  palette:
      primary: custom
      accent: custom
  font:
    text: Inter
    code: Fira Mono
  custom_dir: overrides
  logo: assets/img/transparent.png
  favicon: assets/img/favicon.png
  palette:
    scheme: slate
  features:
    - navigation.sections
    - navigation.expand
    - navigation.tabs
    - navigation.top
    - navigation.breadcrumbs

  plugins:
    - icons

  markdown_extensions:
    - pymdownx.superfences
    - pymdownx.tabbed

extra:
  year: !ENV [YEAR, "2025"]
 
extra_css:
  - assets/css/universal.css
  - assets/css/guides/honey-tree.css
  - assets/css/showcase/showcase.css
  - assets/css/comp/poke-tooltips.css
  - assets/css/showcase/shinywars.css
  - assets/css/utilities/shunt-planner.css

extra_javascript:
  - assets/js/theme-loader.js
  - assets/js/extra.js
  - assets/js/pokemon.js
  - assets/js/word-split.js
  - assets/js/showcase/shinies.js
  - assets/js/showcase/shinywars.js
  - assets/js/utilities/rps/rps.js
  - assets/js/utilities/sp/shunt-planner.js

nav:
  - Home: index.md
  - Guides:
      - Overview: guides/index.md
      - Honey Trees: guides/honey-trees.md
  - Showcase:
      - Overview: showcase/index.md
      - âœ¨ Shiny Wars: showcase/shinywars.md
      - Caught Tracker: showcase/caught.md
  - Utilities:
      - âœ¨ Shunt Planner: utilities/shunt-planner.md
      - Trackers:
        - ğŸ—ºï¸ Pheno Tracker: utilities/pheno-tracker.md
        - ğŸ—ºï¸ Safari Tracker: utilities/safari-tracker.md
        - ğŸ—ºï¸ Legendary Tracker: utilities/legendary-tracker.md
      - Games:
        - ğŸ® Rock, Paper, Scissors: utilities/rps.md
        - ğŸ® Hangman: utilities/hangman.md
  - Database:
      - Bag: 
        - Items: utilities/items.md
        - Medicine: utilities/medicine.md
        - Battle Items: utilities/battle-items.md
        - Key Items: utilities/key-items.md
        - Pokeballs: utilities/pokeballs.md
        - TMs & HMs: utilities/tms-hms.md
        - Berries: utilities/berries.md
        - Cosmetics: utilities/cosmetics.md
      - Pokemon: utilities/pokemon.md
      - Types: utilities/types.md
  
  